### ISSUE TITLE
just a little question

### ISSUE THREAD

**Issue by pog87** [ntustison/antsCorticalThicknessExample#2]
Thank you for this nice example, it was really helpful.
 I am really new to ANTs and I would like to make a little comparison with freesurfer results like in your paper 
https://github.com/ntustison/KapowskiChronicles/blob/master/paper2.pdf?raw=true

How can I obtain mean and sd values for cortical thickness in a standard atlas (say DKT) using ANTs?
For instance I would like to obtain a table like:

Area; ctk; sd
banksst; 3.12;1.12
.........

Thanks for your help,
davide

**Comment by ntustison** [comment]
As we write on page 168 of the paper

> A comparative evaluation between FreeSurfer and ANTs was run on four publicly available data sets: IXI, MMRR, NKI, and OASIS. In addition to these data, we used a subset of the MindBoggle-101 data labeled using the Desikan–Killiany–Tourville (DKT) protocol (Klein and Tourville, 2012) to define the regions of interest (ROI) in the analysis.

Specifically, we used that data and the multi-atlas label fusion algorithm to define the 62 cortical regions for each subject.  Statistics for thickness values can then be calculated for each labeled ROI.

**Comment by pog87** [comment]
Thank you for your answer.
Could you please provide further particulars about your pipeline and maybe some sample commands?

As far as I understand I shall use
antsMalfLabeling.sh with (for instance):
1."tryCorticalThickness.nii.gz" as target [the output from antsCorticalThickness.sh], 
2."t1weightedMNI152.nii.gz" as atlas [a t1w skull-stripped image] and 
3."labels_DKT31_MNI152.nii.gz" as labels [labels in the same space of the previous image]

and run some ImageMath command on the output.

**Comment by ntustison** [comment]
Take a look at this example

https://github.com/ntustison/MalfLabelingExample

**Comment by pog87** [comment]
Ok thanks, it was very useful.
Only one last piece of the puzzle is missing for me.

Given "exampleMalfLabelsResult.nii.gz" and "exampleCorticalThickness.nii.gz" (aligned of course), how to ImageMath a single .csv file with statistics for all ROIs?

 I have been trying by myself since yesterday and I still cannot find how-to (at this point I could write a python script to do that, but I would like to use your same pipeline).

**Comment by ntustison** [comment]
https://github.com/ntustison/Utilities/blob/master/src/LabelIntensityStatistics.cxx

Also, you need to make sure to only include the non-zero thickness values as the MALF ROIs and thickness mask won't perfectly coincide.

**Comment by pog87** [comment]
thank you very much!

I just made ROIs and Thickness coincide, seems to work fine.
My group will now discuss the usage of ANTs in our next works.

If you believe it helps, you could add this topic to your tutorial.

---

“The truth will set you free. But not until it is finished with you.”
DFW
