### ISSUE TITLE
Cortical Segmentation with two modalities failed

### ISSUE THREAD

**Issue by SaskiaBollmann** [ntustison/antsCorticalThicknessExample#3]
Hi,

I used the cortical thickness estimation with an MP2RAGE image and it worked just fine. When adding a FLAIR to get rid of some remaining dura, the cortical thickness estimation fails with the following error:

--------------------------------------------------------------------------------------
Cortical thickness using DiReCT (KellyKapowski)
--------------------------------------------------------------------------------------

BEGIN >>>>>>>>>>>>>>>>>>>>
cp /home/uqsboll2/uq-research/Q0300-P0007TEA/7tea/data/ants_run01/resultsTwoCon/BrainSegmentationPosteriors2.nii.gz /home/uqsboll2/uq-research/Q0300-P0007TEA/7tea/data/ants_run01/resultsTwoCon/CorticalThicknessPosteriors2.nii.gz
cp: cannot stat '/home/uqsboll2/uq-research/Q0300-P0007TEA/7tea/data/ants_run01/resultsTwoCon/BrainSegmentationPosteriors2.nii.gz': No such file or directory
ERROR: command exited with nonzero status 1
Command: cp /home/uqsboll2/uq-research/Q0300-P0007TEA/7tea/data/ants_run01/resultsTwoCon/BrainSegmentationPosteriors2.nii.gz /home/uqsboll2/uq-research/Q0300-P0007TEA/7tea/data/ants_run01/resultsTwoCon/CorticalThicknessPosteriors2.nii.gz

The Posteriors are not there, but I'm not sure why? The BrainExtractionMask.nii and the BrainSegmentation0N4.nii and BrainSegmentation1N4.nii are there, but only ACTStage4Complete.txt.

Maybe you could point me in the direction of what's going wrong?

Thanks and all the best,
Saskia

FYI the command I used

antsCorticalThickness.sh \
-d 3 \
-a ${DATA_DIR}/H0101_T1_orig.nii.gz \
-a ${DATA_DIR}/H0101_T2_orig.nii.gz \
-e ${TEMPLATE_DIR}/T_template.nii.gz \
-t ${TEMPLATE_DIR}/T_template_BrainCerebellum.nii.gz \
-m ${TEMPLATE_DIR}/T_template_BrainCerebellumProbabilityMask.nii.gz \
-f ${TEMPLATE_DIR}/T_template_BrainCerebellumExtractionMask.nii.gz \
-p ${TEMPLATE_DIR}/Priors/priors%d.nii.gz \
-q 1 \
-o ${DATA_DIR}/resultsTwoCon/

**Comment by ntustison** [comment]
Are the T1 and T2 images pre-aligned?

**Comment by SaskiaBollmann** [comment]
I haven't pre-aligned them, but they were acquired within the same session, and the alignment looks good. However, they do have different resolutions and FOV.

**Comment by ntustison** [comment]
They need to be in the same image space---aligned and same image resolution, size, etc.

**Comment by SaskiaBollmann** [comment]
Thanks! The results look beautiful!
